FROM ruby:4.0.2-slim

RUN apt-get update -qq && apt-get install -y \
    build-essential \
    git \
    sqlite3 \
    libsqlite3-dev \
    curl \
    libyaml-dev \
    pkg-config \
    libvips \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /rails

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

EXPOSE 3000

CMD bash -c "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3000"