services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: new_rails_app

    ports:
      - "3000:3000"

    volumes:
      - .:/rails

    stdin_open: true
    tty: true

    environment:
      RAILS_ENV: development